version: "3.5"

services:
  db_hw16:
    container_name: db_hw16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    image: postgres:14.3-alpine
