### GET docs
GET localhost:8080/api/v1/docs

### GET index
GET localhost:8080/api/v1/index

### GET search - good query
GET localhost:8080/api/v1/index/using

### GET search - bad query
GET localhost:8080/api/v1/index/oops

### POST doc - good doc
POST localhost:8080/api/v1/docs
Content-Type: application/json

{}

### PUT doc - good doc
PUT localhost:8080/api/v1/docs/193
Content-Type: application/json

{
  "Title": "The Title"
}


### PUT doc - bad doc
PUT localhost:8080/api/v1/docs/100000
Content-Type: application/json

{}

### PATCH doc - bad doc
PATCH localhost:8080/api/v1/docs/193
Content-Type: application/json

{}
